// Interop tests: every case is checked against bytes produced by the real C#
// MemoryPack library (tests/fixtures/*.bin, generated by tools/FormatProbe).
//
// For each fixture we assert both directions:
//   1. the C++ reader decodes the C# bytes to the expected values, and
//   2. the C++ writer re-emits byte-identical output.
//
// Optionally a directory can be passed on the command line; the C++-produced
// bytes are written there so `FormatProbe check-cpp <dir>` can confirm that C#
// reads them back correctly.

#include "interop_types.hpp"
#include "test_harness.hpp"

#include <cmath>
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <string>
#include <vector>

using namespace memorypack;
namespace fs = std::filesystem;

namespace {

fs::path g_fixtureDir;
fs::path g_outputDir;
int g_missing = 0;

std::vector<uint8_t> LoadFixture(const std::string& name) {
    const fs::path path = g_fixtureDir / (name + ".bin");
    std::ifstream in(path, std::ios::binary);
    if (!in) {
        ++g_missing;
        std::printf("  [MISS] fixture not found: %s\n", path.string().c_str());
        return {};
    }
    return std::vector<uint8_t>((std::istreambuf_iterator<char>(in)),
                                 std::istreambuf_iterator<char>());
}

void SaveOutput(const std::string& name, std::span<const uint8_t> bytes) {
    if (g_outputDir.empty()) return;
    std::ofstream out(g_outputDir / (name + ".bin"), std::ios::binary);
    out.write(reinterpret_cast<const char*>(bytes.data()),
              static_cast<std::streamsize>(bytes.size()));
}

/// Round-trips one fixture: decode the C# bytes, hand the value to `verify`,
/// then re-encode and require byte equality with the C# output.
template<typename T, typename Verify>
void Roundtrip(const std::string& name, Verify&& verify) {
    TEST_CASE(name.c_str());
    const auto expected = LoadFixture(name);
    if (expected.empty() && g_missing) return;

    T value{};
    MemoryPackReader reader(expected);
    reader.Read(value);
    CHECK_MSG(!reader.Failed(), "reader reported an error decoding the C# bytes");
    CHECK_MSG(reader.IsEnd(), "reader did not consume the whole C# payload");
    verify(value);

    const auto actual = Serialize(value);
    CHECK_BYTES_EQ(std::span<const uint8_t>(actual), std::span<const uint8_t>(expected),
                   "re-serialized bytes differ from C# MemoryPack");
    SaveOutput(name, actual);
}

/// Same, but the value is supplied rather than decoded - for cases where the
/// C++ type cannot represent the fixture on its own (top-level nulls).
template<typename T, typename Verify>
void RoundtripValue(const std::string& name, const T& seed, Verify&& verify) {
    TEST_CASE(name.c_str());
    const auto expected = LoadFixture(name);
    if (expected.empty() && g_missing) return;

    T value = seed;
    MemoryPackReader reader(expected);
    reader.Read(value);
    CHECK_MSG(!reader.Failed(), "reader reported an error decoding the C# bytes");
    verify(value);

    const auto actual = Serialize(value);
    CHECK_BYTES_EQ(std::span<const uint8_t>(actual), std::span<const uint8_t>(expected),
                   "re-serialized bytes differ from C# MemoryPack");
    SaveOutput(name, actual);
}

bool NearlyEqual(float a, float b) { return std::fabs(a - b) < 1e-6f; }

// ── Cases ──────────────────────────────────────────────────────────────────────

void TestObjects() {
    Roundtrip<interop::SimplePacket>("simple_packet", [](const auto& v) {
        CHECK(v.id == 42);
        CHECK(v.name == "ABC");
    });

    Roundtrip<interop::AllPrimitives>("all_primitives", [](const auto& v) {
        CHECK(v.boolValue == true);
        CHECK(v.byteValue == 200);
        CHECK(v.sbyteValue == -5);
        CHECK(v.shortValue == -1234);
        CHECK(v.ushortValue == 54321);
        CHECK(v.intValue == -123456);
        CHECK(v.uintValue == 3000000000u);
        CHECK(v.longValue == -1234567890123LL);
        CHECK(v.ulongValue == 12345678901234567890ULL);
        CHECK(v.floatValue == 3.14159f);
        CHECK(v.doubleValue == 2.718281828459045);
    });

    Roundtrip<interop::EmptyPacket>("empty_packet", [](const auto&) {});

    Roundtrip<interop::ManyMembers>("many_members", [](const auto& v) {
        CHECK(v.m00 == 0 && v.m04 == 4 && v.m09 == 9);
    });

    Roundtrip<interop::OrderedPacket>("ordered_packet", [](const auto& v) {
        CHECK(v.first == 1);
        CHECK(v.second == 2);
    });

    // A top-level null object is a single 0xFF byte.
    TEST_CASE("null_object");
    {
        const auto expected = LoadFixture("null_object");
        if (!expected.empty()) {
            CHECK(expected.size() == 1 && expected[0] == NULL_OBJECT);
            MemoryPackWriter w;
            w.WritePointer<interop::SimplePacket>(nullptr);
            CHECK_BYTES_EQ(w.GetSpan(), std::span<const uint8_t>(expected), "null object header");
            SaveOutput("null_object", w.GetSpan());
        }
    }

    Roundtrip<interop::NestedObject>("nested_object", [](const auto& v) {
        CHECK(v.id == 5);
        CHECK(v.child.has_value());
        if (v.child) {
            CHECK(v.child->itemId == 9);
            CHECK(v.child->itemName == "Gem");
            CHECK(v.child->count == 3);
        }
    });

    Roundtrip<interop::NullMembers>("null_members", [](const auto& v) {
        CHECK(!v.nullString.has_value());
        CHECK(v.emptyString.empty());
        CHECK(!v.nullList.has_value());
        CHECK(v.emptyList.empty());
        CHECK(!v.nullChild.has_value());
    });
}

void TestEnums() {
    Roundtrip<interop::EnumPacket>("enum_packet", [](const auto& v) {
        CHECK(v.u16 == interop::ColorU16::Green);
        CHECK(v.i8 == interop::ColorI8::Neg);
        CHECK(v.i32 == interop::ColorI32::B);
    });
}

void TestStrings() {
    Roundtrip<interop::StringPacket>("string_packet", [](const auto& v) {
        CHECK(v.ascii == "Hello");
        CHECK(v.korean == "\xED\x95\x9C\xEA\xB8\x80");     // 한글
        CHECK(v.emoji == "\xF0\x9F\x98\x80");              // U+1F600
        CHECK(v.empty.empty());
        CHECK(!v.nullString.has_value());
    });

    Roundtrip<std::string>("string_top_level", [](const auto& v) { CHECK(v == "Hello"); });
    Roundtrip<std::string>("string_top_level_empty", [](const auto& v) { CHECK(v.empty()); });

    RoundtripValue<std::optional<std::string>>("string_top_level_null", std::string("seed"),
        [](const auto& v) { CHECK(!v.has_value()); });

    // A UTF-8 payload can be viewed without copying.
    TEST_CASE("string_view_zero_copy");
    {
        const auto bytes = LoadFixture("string_top_level");
        if (!bytes.empty()) {
            MemoryPackReader r(bytes);
            auto view = r.ReadStringView();
            CHECK(view.has_value() && *view == "Hello");
            CHECK_MSG(view && view->data() >= reinterpret_cast<const char*>(bytes.data()) &&
                          view->data() < reinterpret_cast<const char*>(bytes.data()) + bytes.size(),
                      "the view must point into the input buffer, not a copy");
        }
    }
}

void TestCollections() {
    Roundtrip<interop::ArrayPacket>("array_packet", [](const auto& v) {
        CHECK((v.shorts == std::vector<int16_t>{1, -2, 3}));
        CHECK((v.ints == std::vector<int32_t>{10, 20, 30}));
        CHECK((v.longs == std::vector<int64_t>{-1, 2}));
        CHECK((v.bytes == std::vector<uint8_t>{0, 128, 255}));
        CHECK((v.sbytes == std::vector<int8_t>{-128, 0, 127}));
        CHECK((v.floats == std::vector<float>{1.5f, -2.5f}));
        CHECK((v.doubles == std::vector<double>{1.25, -2.5}));
        CHECK((v.strings == std::vector<std::string>{"a", "bb", "ccc"}));
    });

    Roundtrip<std::vector<int32_t>>("int_list_top_level", [](const auto& v) {
        CHECK((v == std::vector<int32_t>{10, 20, 30}));
    });
    Roundtrip<std::vector<int32_t>>("int_list_empty", [](const auto& v) { CHECK(v.empty()); });

    RoundtripValue<std::optional<std::vector<int32_t>>>(
        "int_list_null", std::vector<int32_t>{1, 2},
        [](const auto& v) { CHECK(!v.has_value()); });

    Roundtrip<interop::BoolCollection>("bool_collection", [](const auto& v) {
        CHECK((v.flags == std::vector<bool>{true, false, true}));
        CHECK((v.flagArray == std::vector<bool>{false, true}));
    });

    Roundtrip<interop::NestedList>("nested_list", [](const auto& v) {
        CHECK(v.rows.size() == 3);
        if (v.rows.size() == 3) {
            CHECK((v.rows[0] == std::vector<int32_t>{1, 2}));
            CHECK((v.rows[1] == std::vector<int32_t>{3}));
            CHECK(v.rows[2].empty());
        }
    });

    Roundtrip<interop::Inventory>("inventory", [](const auto& v) {
        CHECK(v.ownerId == 7);
        CHECK(v.items.size() == 3);
        if (v.items.size() == 3) {
            CHECK(v.items[0].itemId == 1 && v.items[0].itemName == "Sword" && v.items[0].count == 10);
            CHECK(v.items[1].itemName == "Shield");
            CHECK(v.items[2].itemName == "Potion" && v.items[2].count == 30);
        }
    });

    Roundtrip<interop::ListOfNullableObjects>("list_of_nullable_objects", [](const auto& v) {
        CHECK(v.items.size() == 2);
        if (v.items.size() == 2) {
            CHECK(v.items[0].has_value() && v.items[0]->itemName == "A");
            CHECK(!v.items[1].has_value());
        }
    });
}

void TestMapsAndSets() {
    Roundtrip<interop::DictPacket>("dict_packet", [](const auto& v) {
        CHECK(v.intMap.size() == 3 && v.intMap.at(2) == 20);
        CHECK(v.stringMap.size() == 2 && v.stringMap.at("b") == 2);
        CHECK(v.intToString.size() == 2 && v.intToString.at(1) == "one");
    });

    Roundtrip<interop::DictObjectPacket>("dict_object_packet", [](const auto& v) {
        CHECK(v.items.size() == 1);
        if (v.items.contains(1)) CHECK(v.items.at(1).itemName == "A");
    });

    Roundtrip<interop::SetPacket>("set_packet", [](const auto& v) {
        CHECK(v.intSet.size() == 3 && v.intSet.contains(30));
        CHECK(v.stringSet.size() == 2 && v.stringSet.contains("beta"));
    });

    Roundtrip<interop::KvpPacket>("kvp_packet", [](const auto& v) {
        CHECK(v.intPair.first == 1 && v.intPair.second == 2);
        CHECK(v.mixedPair.first == 3 && v.mixedPair.second == "kv");
    });
}

void TestUnmanaged() {
    Roundtrip<interop::Vec3>("vec3_top_level", [](const auto& v) {
        CHECK(v.x == 1.5f && v.y == 2.5f && v.z == 3.5f);
    });

    Roundtrip<interop::PaddedStruct>("padded_struct_top_level", [](const auto& v) {
        CHECK(v.tag == 7 && v.value == 1000);
    });

    Roundtrip<interop::PackedStruct>("packed_struct_top_level", [](const auto& v) {
        CHECK(v.tag == 7 && v.value == 1000);
    });

    Roundtrip<interop::UnmanagedHolder>("unmanaged_holder", [](const auto& v) {
        CHECK(v.position.x == 1.5f && v.position.z == 3.5f);
        CHECK(v.padded.tag == 7 && v.padded.value == 1000);
    });

    Roundtrip<interop::UnmanagedList>("unmanaged_list", [](const auto& v) {
        CHECK(v.points.size() == 2);
        if (v.points.size() == 2) {
            CHECK(v.points[0].x == 1.f && v.points[0].z == 3.f);
            CHECK(v.points[1].x == 4.f && v.points[1].z == 6.f);
        }
    });

    Roundtrip<interop::ManagedStructHolder>("managed_struct_holder", [](const auto& v) {
        CHECK(v.value.id == 4 && v.value.label == "lbl");
    });

    Roundtrip<interop::NumericsTypes>("numerics_types", [](const auto& v) {
        CHECK(v.v2.x == 1.f && v.v2.y == 2.f);
        CHECK(v.v3.z == 5.f);
        CHECK(v.v4.w == 9.f);
        CHECK(NearlyEqual(v.quat.w, 0.4f));
    });
}

void TestNullable() {
    Roundtrip<interop::NullablePacket>("nullable_packet", [](const auto& v) {
        CHECK(v.maybeInt.has_value() && *v.maybeInt == 99);
        CHECK(!v.nullInt.has_value());
        CHECK(v.maybeFloat.has_value() && *v.maybeFloat == 1.25f);
        CHECK(v.maybeVec.has_value() && v.maybeVec->x == 1.f && v.maybeVec->z == 3.f);
        CHECK(!v.nullVec.has_value());
    });

    Roundtrip<std::optional<int32_t>>("nullable_int_top_level", [](const auto& v) {
        CHECK(v.has_value() && *v == 42);
    });

    RoundtripValue<std::optional<int32_t>>("nullable_int_top_level_null", std::optional<int32_t>(7),
        [](const auto& v) { CHECK(!v.has_value()); });

    Roundtrip<interop::NullableManagedHolder>("nullable_managed_holder", [](const auto& v) {
        CHECK(v.value.has_value());
        if (v.value) CHECK(v.value->a == 3 && v.value->b == "n");
    });

    Roundtrip<interop::NullableManagedHolder>("nullable_managed_holder_null", [](const auto& v) {
        CHECK(!v.value.has_value());
    });
}

void TestTuples() {
    Roundtrip<interop::TuplePacket>("value_tuple", [](const auto& v) {
        CHECK(v.refTuple.has_value());
        if (v.refTuple) {
            CHECK(std::get<0>(*v.refTuple) == 7);
            CHECK(std::get<1>(*v.refTuple) == "ref");
        }
        CHECK(v.unmanagedValueTuple.item1 == 11 && v.unmanagedValueTuple.item2 == 22);
        CHECK(v.mixedValueTuple.first == 33 && v.mixedValueTuple.second == "tuple");
        CHECK(v.tripleUnmanaged.item1 == 44);
        CHECK(v.tripleUnmanaged.item2 == 1.5f);
        CHECK(v.tripleUnmanaged.item3 == 2.5);
    });

    Roundtrip<interop::ValueTuple2i>("value_tuple_top_level", [](const auto& v) {
        CHECK(v.item1 == 11 && v.item2 == 22);
    });
}

void TestDotNetTypes() {
    Roundtrip<interop::DotNetTypes>("dotnet_types", [](const auto& v) {
        CHECK(v.guidValue.ToString() == "01020304-0506-0708-090a-0b0c0d0e0f10");
        CHECK(v.dateTimeValue.GetKind() == DateTimeKind::Utc);
        CHECK(v.timeSpanValue.ticks == 900000000LL);   // 90 seconds
        CHECK(v.dateTimeOffsetValue.offsetMinutes == 540);   // +09:00
        CHECK(v.charValue == u'A');
        CHECK(NearlyEqual(v.halfValue.ToFloat(), 1.5f));
        CHECK(v.int128Value.high == static_cast<int64_t>(0x8000000000000000ULL));
        CHECK(v.int128Value.low == 7);
        CHECK(v.uint128Value.low == 123456789 && v.uint128Value.high == 0);
    });

    Roundtrip<Guid>("guid_top_level", [](const auto& v) {
        CHECK(v.ToString() == "01020304-0506-0708-090a-0b0c0d0e0f10");
        auto parsed = Guid::Parse("01020304-0506-0708-090a-0b0c0d0e0f10");
        CHECK(parsed.has_value() && *parsed == v);
    });

    Roundtrip<DateTime>("datetime_top_level", [](const auto& v) {
        CHECK(v.GetKind() == DateTimeKind::Utc);
        // 2026-08-30T12:34:56Z
        const auto tp = v.ToTimePoint();
        const auto secs = std::chrono::duration_cast<std::chrono::seconds>(
                              tp.time_since_epoch()).count();
        CHECK(secs == 1788093296LL);
    });
}

void TestUnions() {
    Roundtrip<interop::UnionHolder>("union_circle", [](const auto& v) {
        CHECK(v.shape.has_value());
        CHECK(v.shape && std::holds_alternative<interop::CircleShape>(*v.shape));
        if (v.shape && std::holds_alternative<interop::CircleShape>(*v.shape))
            CHECK(std::get<interop::CircleShape>(*v.shape).radius == 2.5f);
    });

    Roundtrip<interop::UnionHolder>("union_rect", [](const auto& v) {
        CHECK(v.shape && std::holds_alternative<interop::RectShape>(*v.shape));
        if (v.shape && std::holds_alternative<interop::RectShape>(*v.shape)) {
            const auto& r = std::get<interop::RectShape>(*v.shape);
            CHECK(r.width == 3.f && r.height == 4.f);
        }
    });

    // Tag 300 exercises the wide-tag encoding: [250][uint16 tag].
    Roundtrip<interop::UnionHolder>("union_wide", [](const auto& v) {
        CHECK(v.shape && std::holds_alternative<interop::WideShape>(*v.shape));
        if (v.shape && std::holds_alternative<interop::WideShape>(*v.shape))
            CHECK(std::get<interop::WideShape>(*v.shape).sides == 12);
    });

    Roundtrip<interop::UnionHolder>("union_null", [](const auto& v) {
        CHECK(!v.shape.has_value());
    });

    Roundtrip<interop::Shape>("union_top_level", [](const auto& v) {
        CHECK(std::holds_alternative<interop::CircleShape>(v));
    });
}

void TestVersionTolerant() {
    Roundtrip<interop::VersionTolerantPacket>("version_tolerant", [](const auto& v) {
        CHECK(v.id == 77);
        CHECK(v.name == "vt");
        CHECK(v.score == 0.5f);
    });

    // Member-length encodings: single byte, 0x84 + uint16, 0x82 + uint32.
    Roundtrip<interop::VersionTolerantLong>("vt_len_120", [](const auto& v) {
        CHECK(v.id == 1 && v.big.size() == 112 && v.tail == 9);
    });
    Roundtrip<interop::VersionTolerantLong>("vt_len_130", [](const auto& v) {
        CHECK(v.id == 1 && v.big.size() == 122 && v.tail == 9);
    });
    Roundtrip<interop::VersionTolerantLong>("version_tolerant_long", [](const auto& v) {
        CHECK(v.id == 1 && v.big.size() == 300 && v.tail == 9);
    });
    Roundtrip<interop::VersionTolerantLong>("vt_len_70000", [](const auto& v) {
        CHECK(v.id == 1 && v.big.size() == 69992 && v.tail == 9);
    });
}

void TestSpecialFloats() {
    Roundtrip<interop::SpecialFloats>("special_floats", [](const auto& v) {
        CHECK(std::isnan(v.nanF));
        CHECK(std::isinf(v.posInfF) && v.posInfF > 0);
        CHECK(std::isinf(v.negInfF) && v.negInfF < 0);
        CHECK(std::isnan(v.nanD));
        CHECK(std::isinf(v.posInfD) && v.posInfD > 0);
        CHECK(v.negZeroD == 0.0 && std::signbit(v.negZeroD));
    });
}

} // namespace

int main(int argc, char** argv) {
    g_fixtureDir = (argc > 1 && argv[1][0] != '\0') ? fs::path(argv[1])
                                                    : fs::path(MEMORYPACK_FIXTURE_DIR);
    if (argc > 2 && argv[2][0] != '\0') {
        g_outputDir = fs::path(argv[2]);
        std::error_code ec;
        fs::create_directories(g_outputDir, ec);
    }

    std::printf("fixtures: %s\n", g_fixtureDir.string().c_str());
    if (!g_outputDir.empty())
        std::printf("writing C++ output to: %s\n", g_outputDir.string().c_str());
    std::printf("\n");

    TestObjects();
    TestEnums();
    TestStrings();
    TestCollections();
    TestMapsAndSets();
    TestUnmanaged();
    TestNullable();
    TestTuples();
    TestDotNetTypes();
    TestUnions();
    TestVersionTolerant();
    TestSpecialFloats();

    if (g_missing > 0) {
        std::printf("\n%d fixture file(s) were missing. Regenerate them with:\n"
                    "  dotnet run --project tools/FormatProbe -- generate tests/fixtures\n",
                    g_missing);
        return 1;
    }
    return mptest::Summarize("interop_tests");
}
