#!/usr/bin/env python3
"""Combine the MemoryPackCpp headers into a single self-contained header.

The library is normally consumed as a directory of headers, which keeps compile
times down because a project can include only the parts it needs. For people who
would rather drop one file into their tree - and for GitHub release assets - this
script flattens them into `memorypack.hpp`.

Usage:
    python tools/amalgamate.py                      # -> dist/memorypack.hpp
    python tools/amalgamate.py -o build/single.hpp
    python tools/amalgamate.py --include-packet     # also inline packet.hpp

The result is byte-identical in behaviour to including the umbrella header: the
internal `#include "memorypack/..."` lines are replaced by the file contents in
dependency order, every `#pragma once` after the first is dropped, and the system
includes are hoisted to the top and de-duplicated.
"""

from __future__ import annotations

import argparse
import datetime
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
HEADER_DIR = REPO_ROOT / "include" / "memorypack"

# Dependency order: each file may only depend on the ones before it.
CORE_ORDER = ["core.hpp", "containers.hpp", "dotnet.hpp"]
OPTIONAL = ["packet.hpp"]

INTERNAL_INCLUDE = re.compile(r'^\s*#\s*include\s+"memorypack/([A-Za-z0-9_]+\.hpp)"\s*$')
SYSTEM_INCLUDE = re.compile(r"^\s*#\s*include\s+<([^>]+)>\s*$")
PRAGMA_ONCE = re.compile(r"^\s*#\s*pragma\s+once\s*$")


def read_version() -> str:
    """Reads MEMORYPACK_VERSION_STRING out of core.hpp so the banner cannot drift."""
    text = (HEADER_DIR / "core.hpp").read_text(encoding="utf-8")
    match = re.search(r'#define\s+MEMORYPACK_VERSION_STRING\s+"([^"]+)"', text)
    return match.group(1) if match else "unknown"


def git_describe() -> str:
    try:
        out = subprocess.run(
            ["git", "-C", str(REPO_ROOT), "rev-parse", "--short", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
        )
        return out.stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"


def collect(files: list[str]) -> tuple[list[str], list[str]]:
    """Returns (sorted system includes, body lines) for the given header files."""
    system_includes: set[str] = set()
    body: list[str] = []

    for name in files:
        path = HEADER_DIR / name
        if not path.is_file():
            sys.exit(f"amalgamate: missing header {path}")

        body.append("")
        body.append(f"// {'=' * 76}")
        body.append(f"// Begin {name}")
        body.append(f"// {'=' * 76}")

        for line in path.read_text(encoding="utf-8").splitlines():
            if PRAGMA_ONCE.match(line):
                continue
            if INTERNAL_INCLUDE.match(line):
                continue          # inlined by this script
            m = SYSTEM_INCLUDE.match(line)
            if m:
                system_includes.add(m.group(1))
                continue
            body.append(line)

        body.append(f"// End {name}")

    return sorted(system_includes), body


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("-o", "--output", default=str(REPO_ROOT / "dist" / "memorypack.hpp"),
                        help="output path (default: dist/memorypack.hpp)")
    parser.add_argument("--include-packet", action="store_true",
                        help="also inline memorypack/packet.hpp (TCP framing helpers)")
    parser.add_argument("output_positional", nargs="?", default=None,
                        help=argparse.SUPPRESS)
    args = parser.parse_args()

    output = Path(args.output_positional or args.output)
    files = list(CORE_ORDER) + (OPTIONAL if args.include_packet else [])

    system_includes, body = collect(files)

    version = read_version()
    commit = git_describe()
    generated = datetime.date.today().isoformat()

    lines: list[str] = [
        "#pragma once",
        "// MemoryPackCpp - single-header amalgamation",
        "//",
        "// C++23 implementation of the Cysharp MemoryPack binary wire format.",
        "// https://github.com/jacking75/MemoryPackCpp",
        "//",
        f"// Version:   {version}",
        f"// Commit:    {commit}",
        f"// Generated: {generated} by tools/amalgamate.py",
        f"// Contents:  {', '.join(files)}",
        "//",
        "// Do not edit this file directly - edit include/memorypack/*.hpp and",
        "// regenerate it.",
        "",
    ]
    lines += [f"#include <{inc}>" for inc in system_includes]
    lines += body
    lines.append("")

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8", newline="\n")

    size_kb = output.stat().st_size / 1024
    print(f"amalgamate: wrote {output} ({size_kb:.1f} KB, {len(lines)} lines)")
    print(f"            version {version}, commit {commit}, from {', '.join(files)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
